export const CREATE_FILM_REQUEST = "CREATE_FILM_REQUEST";
export const CREATE_FILM_SUCCESS = "CREATE_FILM_SUCCESS";
export const CREATE_FILM_FAILURE = "CREATE_FILM_FAILURE";

export const UPDATE_FILM_REQUEST = "UPDATE_FILM_REQUEST";
export const UPDATE_FILM_SUCCESS = "UPDATE_FILM_SUCCESS";
export const UPDATE_FILM_FAILURE = "UPDATE_FILM_FAILURE";

export const DELETE_FILM_REQUEST = "DELETE_FILM_REQUEST";
export const DELETE_FILM_SUCCESS = "DELETE_FILM_SUCCESS";
export const DELETE_FILM_FAILURE = "DELETE_FILM_FAILURE";