export const CREATE_SNACK_REQUEST = "CREATE_SNACK_REQUEST";
export const CREATE_SNACK_SUCCESS = "CREATE_SNACK_SUCCESS";
export const CREATE_SNACK_FAILURE = "CREATE_SNACK_FAILURE";

export const GET_SNACK_LIST_REQUEST = "GET_SNACK_LIST_REQUEST";
export const GET_SNACK_LIST_SUCCESS = "GET_SNACK_LIST_SUCCESS";
export const GET_SNACK_LIST_FAILURE = "GET_SNACK_LIST_FAILURE";