export const CREATE_SNACK_REQUEST = "CREATE_SNACK_REQUEST";
export const CREATE_SNACK_SUCCESS = "CREATE_SNACK_SUCCESS";
export const CREATE_SNACK_FAILURE = "CREATE_SNACK_FAILURE";

export const ADD_SNACK_LIST_REQUEST = "ADD_SNACK_LIST_REQUEST";
export const ADD_SNACK_LIST_SUCCESS = "ADD_SNACK_LIST_SUCCESS";
export const ADD_SNACK_LIST_FAILURE = "ADD_SNACK_LIST_FAILURE";