export const CREATE_SESSION_REQUEST = "CREATE_SESSION_REQUEST";
export const CREATE_SESSION_SUCCESS = "CREATE_SESSION_SUCCESS";
export const CREATE_SESSION_FAILURE = "CREATE_SESSION_FAILURE";

export const GET_SESSION_LIST_REQUEST = "GET_SESSION_LIST_REQUEST";
export const GET_SESSION_LIST_SUCCESS = "GET_SESSION_LIST_SUCCESS";
export const GET_SESSION_LIST_FAILURE = "GET_SESSION_LIST_FAILURE";

export const UPDATE_SESSION_REQUEST = "UPDATE_SESSION_REQUEST";
export const UPDATE_SESSION_SUCCESS = "UPDATE_SESSION_SUCCESS";
export const UPDATE_SESSION_FAILURE = "UPDATE_SESSION_FAILURE";