export const VIEW_USER_TICKETS_REQUEST = "VIEW_USER_TICKETS_REQUEST";
export const VIEW_USER_TICKETS_SUCCESS = "VIEW_USER_TICKETS_SUCCESS";
export const VIEW_USER_TICKETS_FAILURE = "VIEW_USER_TICKETS_FAILURE";