export const GET_USER_TICKETS_REQUEST = "GET_USER_TICKETS_REQUEST";
export const GET_USER_TICKETS_SUCCESS = "GET_USER_TICKETS_SUCCESS";
export const GET_USER_TICKETS_FAILURE = "GET_USER_TICKETS_FAILURE";