export const VIEW_USER_TICKETS_REQUEST = "VIEW_USER_TICKETS_REQUEST";
export const VIEW_USER_TICKETS_SUCCESS = "VIEW_USER_TICKETS_SUCCESS";
export const VIEW_USER_TICKETS_FAILURE = "VIEW_USER_TICKETS_FAILURE";

export const BOOK_TICKET_REQUEST = "BOOK_TICKET_REQUEST";
export const BOOK_TICKET_SUCCESS = "BOOK_TICKET_SUCCESS";
export const BOOK_TICKET_FAILURE = "BOOK_TICKET_FAILURE";