export const CREATE_SALE_REQUEST = "CREATE_SALE_REQUEST";
export const CREATE_SALE_SUCCESS = "CREATE_SALE_SUCCESS";
export const CREATE_SALE_FAILURE = "CREATE_SALE_FAILURE";

export const GET_SALE_LIST_REQUEST = "GET_SALE_LIST_REQUEST";
export const GET_SALE_LIST_SUCCESS = "GET_SALE_LIST_SUCCESS";
export const GET_SALE_LIST_FAILURE = "GET_SALE_LIST_FAILURE";